"""
AI每日复盘教练 - 核心逻辑模块
负责与AI API交互，生成追问、分析回答、保存复盘结果
"""

import os
import json
import yaml
from datetime import datetime
from pathlib import Path
from openai import OpenAI


def load_config(config_path="config.yaml"):
    """加载配置文件"""
    # 尝试多个路径
    search_paths = [
        config_path,
        Path(__file__).parent.parent.parent / config_path,
        Path.cwd() / config_path,
    ]
    for p in search_paths:
        if Path(p).exists():
            with open(p, "r", encoding="utf-8") as f:
                return yaml.safe_load(f)
    # 如果找不到配置文件，尝试从环境变量读取
    api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("DEEPSEEK_API_KEY")
    if api_key:
        return {
            "api": {
                "base_url": os.environ.get("API_BASE_URL", "https://api.deepseek.com"),
                "api_key": api_key,
                "model": os.environ.get("MODEL_NAME", "deepseek-chat"),
            }
        }
    raise FileNotFoundError(
        "未找到 config.yaml 配置文件。请复制 references/config_example.yaml 为 config.yaml 并填写 API Key。"
    )


def create_client(config):
    """根据配置创建OpenAI客户端"""
    api_config = config["api"]
    return OpenAI(
        api_key=api_config["api_key"],
        base_url=api_config["base_url"],
    )


def chat(client, model, messages, temperature=0.7, max_tokens=2000):
    """调用AI进行对话"""
    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response.choices[0].message.content


# ==================== 第一阶段：生成追问 ====================

QUESTIONS_PROMPT = """你是一个深刻的每日复盘教练。用户刚刚描述了他今天的情况。

请根据用户的描述，生成3个深度追问，帮助用户：
1. 想清楚今天真正重要的是什么
2. 发现被忽略的问题或卡点
3. 找到明天可以改进的具体方向

规则：
- 问题要具体、有洞察力，不能是泛泛而谈的"今天感觉怎么样"
- 每个问题都要基于用户的具体描述来追问
- 问题要有递进关系，引导用户从表面思考到深层

请直接输出3个问题，每行一个，以"1. ""2. ""3. "开头。不要有其他内容。"""


def generate_questions(client, model, user_input):
    """根据用户今日描述，生成3个深度追问"""
    messages = [
        {"role": "system", "content": QUESTIONS_PROMPT},
        {"role": "user", "content": f"今天我复盘的内容是：\n{user_input}"},
    ]
    response = chat(client, model, messages, temperature=0.8, max_tokens=500)
    return response


# ==================== 第二阶段：分析回答 ====================

ANALYSIS_PROMPT = """你是一个专业的每日复盘教练。用户今天的情况、你的追问以及用户的回答如下。

请生成一份复盘分析，包含以下4部分（用Markdown格式）：

## 📌 今日关键事件
用3-5句话提炼今天最重要的几件事，去掉流水账。

## 🔍 卡点分析
识别今天遇到的障碍/困难/卡点，分析根因。如果用户的情绪有问题，也要指出来。

## 💡 明天一个重点建议
只给1条最关键的、明天就能执行的建议。要具体、可衡量，不要假大空。

## 📊 今日状态评分
给今天的整体状态打分（1-10分），并简要说明理由。

要求：
- 语气温暖但有洞察力
- 不灌鸡汤，说真话
- 建议必须可执行，不是"加油"这类空话"""


def analyze_review(client, model, user_input, questions, answers):
    """分析用户的复盘内容，生成结构化复盘报告"""
    qa_text = ""
    q_list = [q.strip() for q in questions.split("\n") if q.strip()]
    a_list = [a.strip() for a in answers.split("\n") if a.strip()]

    for i, (q, a) in enumerate(zip(q_list, a_list)):
        qa_text += f"\n追问{i+1}：{q}\n回答{i+1}：{a}\n"

    user_message = f"""用户今日复盘：
{user_input}

追问与回答：
{qa_text}"""

    messages = [
        {"role": "system", "content": ANALYSIS_PROMPT},
        {"role": "user", "content": user_message},
    ]
    response = chat(client, model, messages, temperature=0.7, max_tokens=1500)
    return response


# ==================== 第三阶段：保存复盘 ====================

def save_review(date_str, user_input, questions, answers, analysis, output_dir="reviews"):
    """将复盘结果保存为Markdown文件"""
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    filename = f"{date_str}_复盘.md"
    filepath = output_path / filename

    content = f"""# 📝 {date_str} 每日复盘

---

## 🗣️ 今日描述
{user_input}

---

## ❓ AI的3个深度追问

{questions}

---

## 💬 我的回答

{answers}

---

{analysis}

---
*Generated by AI每日复盘教练 @ {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return str(filepath)


# ==================== 周度汇总 ====================

WEEKLY_SUMMARY_PROMPT = """你是一个复盘教练。以下是一周（7天）的每日复盘记录。

请生成一份周度汇总报告（Markdown格式），包含：

## 📈 本周整体状态
用3-5句话概括这一周的整体情况。

## 🔁 重复出现的问题
分析哪些问题在本周反复出现，按严重程度排序。

## ✅ 做得好的地方
本周有哪些值得肯定的进步或坚持。

## 🎯 下周关键建议
给2-3条下周最应该关注的改进方向。

## 📊 周度评分
给本周打一个总分（1-10分），并给出简短理由。

要求：
- 基于实际数据，不编造
- 发现问题要直接指出，不拐弯抹角
- 建议要具体可执行"""


def generate_weekly_summary(client, model, reviews_text):
    """生成周度汇总报告"""
    messages = [
        {"role": "system", "content": WEEKLY_SUMMARY_PROMPT},
        {"role": "user", "content": f"以下是本周的复盘记录：\n\n{reviews_text}"},
    ]
    response = chat(client, model, messages, temperature=0.7, max_tokens=2000)
    return response


def load_week_reviews(reviews_dir="reviews", date_prefix=""):
    """加载指定周的复盘文件"""
    reviews_path = Path(reviews_dir)
    if not reviews_path.exists():
        return ""

    all_text = ""
    for f in sorted(reviews_path.glob("*.md")):
        if date_prefix and not f.stem.startswith(date_prefix):
            continue
        with open(f, "r", encoding="utf-8") as fp:
            all_text += f"\n---\n## 文件：{f.name}\n\n{fp.read()}\n"

    return all_text
